// Token list - generated by gentoks.py from etokens

#include "tokeniser.h"
extern TokenRegistry etokens[];
#define	T_END	0
#define	T_STRING	1
#define	T_IDENT	2
#define	T_INT	3
#define	T_FLOAT	4
#define	T_OPREN	5
#define	T_CPREN	6
#define	T_MUL	7
#define	T_ADD	8
#define	T_SUB	9
#define	T_DIV	10
#define	T_EQ	11
#define	T_PLING	12
#define	T_LT	13
#define	T_GT	14
#define	T_AND	15
#define	T_OR	16
