// Token table - generated by gentoks.py from etokens

#include "etokens.h"
TokenRegistry etokens[] = {
	{"*e", T_END},
	{"*s", T_STRING},
	{"*i", T_IDENT},
	{"*n", T_INT},
	{"*f", T_FLOAT},
	{"*c(", T_OPREN},
	{"*c)", T_CPREN},
	{"*c*", T_MUL},
	{"*c+", T_ADD},
	{"*c-", T_SUB},
	{"*c/", T_DIV},
	{"*c=", T_EQ},
	{"*c!", T_PLING},
	{"*c<", T_LT},
	{"*c>", T_GT},
	{"&&", T_AND},
	{"||", T_OR},
{NULL,-10}
};
